name: Deploy Git Action

on:
  push:
    branches:
      - main
# 작업 지시 
jobs:
  deploy:
    runs-on: self-hosted #현재 Ubuntu에 배포
    # 소스 코드 다운로드 = clone과 통일
    steps:
      - uses: actions/chechout@v4
      # JDK 21버전 확인
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      # gradlew 권한 부여
      - run: chmod +x gradlew
      #빌드 
      - run: ./gradlew clean build -x test
      # 실행 => jar파일 생성 => java -jar app.jar
      - run: |
          PID=$(lsof -t -i:8080 || true)
          if [-n "$PID" ]; then
             kill -15 "$PID" || true
          fi  
        env:
            RUNNER_TRACKING_ID: ""    
      - run: nohup java -jar build/libs/*.0.0.1-SNAPSHOT.jar > app.log 2>&1 &    
